### ISSUE TITLE
[Request] Reboot option

### ISSUE THREAD

**Issue by NayamAmarshe** [Davide-sd/shutdown_or_switch#1]
Hi! Would it be possible to add a Reboot option besides the default options of New Session, Shutdown and Lockscreen? The widget is perfect, just needs a reboot option that's all :D

**Comment by Davide-sd** [comment]
Hello. Honestly, I have no idea. It's something I looked for when I created the plugin but I was unable to find help (not in the forum nor in the documentation). I doubt things have improved on both side so I'm not going to invest time in it. If you'd like to take a shot at it, by any mean, go ahead! I moved on to use Lock/Logout (which should come standard with KDE) just because of the missing reboot.

**Comment by NayamAmarshe** [comment]
> Hello. Honestly, I have no idea. It's something I looked for when I created the plugin but I was unable to find help (not in the forum nor in the documentation). I doubt things have improved on both side so I'm not going to invest time in it. If you'd like to take a shot at it, by any mean, go ahead! I moved on to use Lock/Logout (which should come standard with KDE) just because of the missing reboot.

I can try but I'm no Qt developer. I saw the code of the Kpple Menu though, it seems like the dev was using actual unix commands for reboot, shutdown rather than the ones provided by the API.

**Comment by Davide-sd** [comment]
Thanks @NayamAmarshe for the taking the time to add it. After your PR, I was able to add a few more buttons (Suspend, Hybernate) as well a few configuration options to only show the interested buttons. Thank you!

I'm closing this issue!
