### ISSUE TITLE
Support Plasma 6 (Port to KF6)

### ISSUE THREAD

**Issue by Svenum** [Davide-sd/shutdown_or_switch#6]
Please port this widget to KDE Framework 6. The guidelines are [here](https://develop.kde.org/docs/plasma/widget/porting_kf6/).

**Comment by Svenum** [comment]
I have written my own version of this Plasmoid. Feel free to use it and make issues if needed. :) 
https://github.com/Svenum/quick_shutdown

**Comment by Davide-sd** [comment]
Hello @Svenum ,

Thanks for letting me know about Plasma 6, and sorry for my late reply.

How does your plugin differ from mine, except being written for Plasma 6?

Also, I assume that in order to test a Plasma 6 widgets, Plasma 6 must be installed on the system. Do you know of any Debian-based distribution that ships with it?

**Comment by Svenum** [comment]
I have taken the 'user-switch' plugin as a base like you. And then add the options for the power modes. To shutdown and reboot and so on I use the session manager instead of dbus calls.

**Comment by Svenum** [comment]
If you want I can make an PR for my version into your repo, or would you contribute to my if you are not so active on GitHub?
